### ISSUE TITLE
Make translations support configurable

### ISSUE THREAD

**Issue by danekja** [danekja/ymanager#36]
Current cz.zcu.yamanager.util.localization.Message class is implemented with singleton (well, broken singleton) pattern which makes it difficult to configure and test.

Related test suite crashes unless tests are run in specific order.

**Comment by danekja** [comment]
We might also consider dropping localization from backend and make only the UI localized. What do you think @fidransky?

**Comment by fidransky** [comment]
The app only used l10n for exception messages. Dropped.
